services:
  tf-lab:
    build: .
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - ./work:/tf/work
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
